CREATE TABLE `team` (
	`id` BIGSERIAL NOT NULL,
	`team_name` VARCHAR(128) NOT NULL,
	`task_id` BIGINT NOT NULL,
	CONSTRAINT team_ak_1 UNIQUE (team_name) NOT DEFERRABLE  INITIALLY IMMEDIATE,
	PRIMARY KEY (`id`)
);